-- MySQL Script generated by MySQL Workbench
-- 11/14/17 13:04:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Chat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Chat` DEFAULT CHARACTER SET utf8 ;
USE `Chat` ;

-- -----------------------------------------------------
-- Table `Chat`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Chat`.`Message` (
  `idMessage` INT NOT NULL,
  `text` TEXT NULL,
  `userName` TEXT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`idMessage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chat`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Chat`.`Users` (
  `idUsers` INT NOT NULL,
  `userName` TEXT NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
